### ISSUE TITLE
[Bug] Restarting HA/Panel

### ISSUE THREAD

**Issue by mainmind83** [NSPManager/NSPanelManager#86] opened 2023-09-06 10:23 UTC
If Home Assistant is restarted and the panel is still active, when HA starts, the panel appears as connected in the Manager but the screen shows "registering to manager"

**Comment by tpanajott** [comment] 2023-09-06 10:28
Yhea, the manager only looks at the mqtt status topic for the panel and if it's state is "online", that will however occur as long as it's connected to mqtt and might be before it has registered to the manager. As said in another post, this handshake between the manager and the panel is being reworked.

**Comment by mainmind83** [comment] 2023-09-06 10:28
If the IP of the panel changes, it is not updated either

**Comment by tpanajott** [comment] 2023-09-06 10:31
> If the IP of the panel changes, it is not updated either

What do you mean not updated? Not automatically updated on the page without a refresh or that it doesn't even show the correct IP after you reload the page?

**Comment by mainmind83** [comment] 2023-09-06 10:33
Not show the correct/new IP of Panel...

With new IP when this screen appear, trying access show "page Not found" on browser too

**Comment by tpanajott** [comment] 2023-09-06 10:34
I'm assuming you are running it as a HA add-on?

**Comment by mainmind83** [comment] 2023-09-06 10:37
yes, HA add-on with NSpanel v1.0 Protocol (by default)

**Comment by tpanajott** [comment] 2023-09-06 10:38
The protocol is just for when updating the screen, v1.2 is faster :)

**Comment by mainmind83** [comment] 2023-09-07 08:35
> The protocol is just for when updating the screen, v1.2 is faster :)

So it should be enabled by default when loading firmware ;D

**Comment by tpanajott** [comment] 2023-09-07 08:51
> So it should be enabled by default when loading firmware ;D

Yes, and I thought it was. What browser were you using at first setup?

**Comment by mainmind83** [comment] 2023-09-08 11:42
Chrome

**Comment by tpanajott** [comment] 2024-08-31 20:33
Closing this issue as I can't reproduce it. Please test with the current beta software or wait for it to go as the new stable and see if you still have the same issue. If so, please reopen this issue and send over the logs.

**Closed by tpanajott** 2024-08-31 20:33 UTC
