### ISSUE TITLE
[Enhancement] (At least for HA), Display Friendly Name Instead of/In Addition To Entity ID

### ISSUE THREAD

**Issue by BrettEBowman** [NSPManager/NSPanelManager#106] opened 2023-10-29 23:10 UTC
I'm only using NSPanelManager with HA (with the HA Addon), so I don't know how it works with OpenHAB or standalone. With the HA add-on, when it lists lights (in the Rooms screens, the panel settings screens, etc. plus on the panel screen) just display the HA Entity ID ("light.xxxx") and not the HA Friendly Name. More and more, then Entity IDs are generic and include device identifiers (like MAC address) and don't necessarily identify the actual light. For instance, see "light.smart_dimmer_switch_std_touch_2_light" on this screen:
![Screenshot 2023-10-29 190251](https://github.com/NSPManager/NSPanelManager/assets/17341309/84a08868-5383-4f4a-b425-d8c477662d05)
The Friendly Name for that device is "Deck Lights":
![Screenshot 2023-10-29 190751](https://github.com/NSPManager/NSPanelManager/assets/17341309/114e9454-dfe9-465b-b751-4b9aeb9eb8ea)

It would be great to at least have the Friendly Name displayed when selecting entities. And it would be preferable to then use the Friendly Name to display the light both in setting screens and on the panel.

**Comment by lucasfeijo** [comment] 2023-10-31 00:47
FYI you can go in edit and change that entity ID to a friendly name, it will remain working as intended. That said, I think it still should be fixed to use the friendly name automatically.

**Comment by BrettEBowman** [comment] 2023-10-31 01:03
@lucasfeijo Thanks for that info. I had discovered that I could go in there afterwards and make the name friendlier. Which is helpful. But it doesn't help with finding the correct device to add in the first place when only the obscure Entity IDs are listed.

**Comment by tpanajott** [comment] 2023-12-25 12:18
Thanks you for reporting this enhancement. This is now implemented in the upcoming release of the new MQTTManager. I will leave it open until we have release the new MQTTManager as stable.

**Closed** 2024-09-01 09:47 UTC
