### ISSUE TITLE
SCREENSAVER MODE - Time 00:00 when sending command to screensaver_mode topic 

### ISSUE THREAD

**Issue by cablesandcoffee** [NSPManager/NSPanelManager#146] opened 2024-04-12 20:14 UTC
**Describe the bug**
The first time you send a command to screensaver_mode topic and change from weather->no weather or no weather->weather clock shows 00:00. After a while the time updates and everything is fine. My guess is that it is because this changes the page to the second screensaver page and the time hasn't been set on that entity yet and is not automatically updated when the user chooses to switch screensaver_mode. A small issue since it only happens the first time after a reboot and the time is eventually updated but would look better if it was updated straight away.

**To Reproduce**
1. Set panel setting on the manager to Show With Background 
2. Reboot panel
3. Send "date_time_withbackground" to topic: screensaver_mode
4. Clock shows 00:00
5. About 60 seconds later time is updated correctly.

**Expected behavior**
Time is updated straight away when screensaver_mode changes. 

**Environment info (please complete the following information):**
 - Home Assistant or Openhab user
 - NSPanelManager version [Web UI lower left corner]
 - NSPanel Firmware version [Visit NSPanel webpage to check]

**Comment by tpanajott** [comment] 2024-04-14 11:40
This was caused by the same problem as #148 which is now fixed, closing this issue.

**Closed by tpanajott** 2024-04-14 11:40 UTC
Labels: bug
